package com.beshara.csc.nl.qul.integration.presentation.backingbean.exception;

import com.beshara.csc.sharedutils.business.exception.SharedApplicationException;

public class QulPrimaryKeyDuplicatedException extends SharedApplicationException {

/**
 *
 * @since 25/11/2015
 * @updatedBy TechnicalTeam [A.Agamy]
 * @Note added new constractors to pass exception
 * constructors generated by ExceptionHandlerProcessor
 */

	@SuppressWarnings("compatibility:-4485906751177687898")
	private static final long serialVersionUID = 1L;
	public static final String DEF_MSG = "QulPrimaryKeyDuplicatedException";
	public static final String MSG_KEY = "QulPrimaryKeyDuplicatedException";
	public static final String BDL_KEY = "QulPrimaryKeyDuplicatedException";

	public QulPrimaryKeyDuplicatedException(String message, Throwable e, String bundleKey, String messageKey){
	super(message, e, bundleKey, messageKey);
	}


	public QulPrimaryKeyDuplicatedException(String message, Throwable e, String messageKey){
	super(message, e, BDL_KEY, messageKey);
	}


	public QulPrimaryKeyDuplicatedException(String message, Throwable e){
	super(message, e, BDL_KEY, MSG_KEY);
	}


	public QulPrimaryKeyDuplicatedException(Throwable e, String bundleKey, String messageKey){
	super(DEF_MSG, e, bundleKey, messageKey);
	}


	public QulPrimaryKeyDuplicatedException(Throwable e, String messageKey){
	super(DEF_MSG, e, BDL_KEY, messageKey);
	}


	public QulPrimaryKeyDuplicatedException(Throwable e){
	super(DEF_MSG, e, BDL_KEY, MSG_KEY);
	}


	public QulPrimaryKeyDuplicatedException(String message, String bundleKey, String messageKey){
	super(message, bundleKey, messageKey);
	}


	public QulPrimaryKeyDuplicatedException(String message, String messageKey){
	super(message, BDL_KEY, messageKey);
	}


    public QulPrimaryKeyDuplicatedException() {

	super(DEF_MSG, BDL_KEY, MSG_KEY);

    }
    
	public QulPrimaryKeyDuplicatedException(String message){

	super(message, BDL_KEY, MSG_KEY);

    }
}





