package com.beshara.csc.inf.business.exception;

import com.beshara.csc.sharedutils.business.exception.SharedApplicationException;

import javax.ejb.ApplicationException;
 
public class DuplicatedNameException extends SharedApplicationException {

/**
 *
 * @since 25/11/2015
 * @updatedBy TechnicalTeam [A.Agamy]
 * @Note added new constractors to pass exception
 * constructors generated by ExceptionHandlerProcessor
 */

	@SuppressWarnings("compatibility:-4485906751177687898")
	private static final long serialVersionUID = 1L;
	public static final String DEF_MSG = "DuplicatedNameException";
	public static final String MSG_KEY = "DuplicatedNameException";
	public static final String BDL_KEY = "DuplicatedNameException";

	public DuplicatedNameException(String message, Throwable e, String bundleKey, String messageKey){
	super(message, e, bundleKey, messageKey);
	}


	public DuplicatedNameException(String message, Throwable e, String messageKey){
	super(message, e, BDL_KEY, messageKey);
	}


	public DuplicatedNameException(String message, Throwable e){
	super(message, e, BDL_KEY, MSG_KEY);
	}


	public DuplicatedNameException(Throwable e, String bundleKey, String messageKey){
	super(DEF_MSG, e, bundleKey, messageKey);
	}


	public DuplicatedNameException(Throwable e, String messageKey){
	super(DEF_MSG, e, BDL_KEY, messageKey);
	}


	public DuplicatedNameException(Throwable e){
	super(DEF_MSG, e, BDL_KEY, MSG_KEY);
	}


	public DuplicatedNameException(String message, String bundleKey, String messageKey){
	super(message, bundleKey, messageKey);
	}


	public DuplicatedNameException(String message, String messageKey){
	super(message, BDL_KEY, messageKey);
	}


    public DuplicatedNameException() {

	super(DEF_MSG, BDL_KEY, MSG_KEY);

    }

	public DuplicatedNameException(String message){

	super(message, BDL_KEY, MSG_KEY);

    }
}
