package com.beshara.csc.inf.business.exception;

import com.beshara.csc.sharedutils.business.exception.SharedApplicationException;

import javax.ejb.ApplicationException;
 
public class EmployeeCivilIdNotExistException extends SharedApplicationException {

/**
 *
 * @since 25/11/2015
 * @updatedBy TechnicalTeam [A.Agamy]
 * @Note added new constractors to pass exception
 * constructors generated by ExceptionHandlerProcessor
 */

    @SuppressWarnings("compatibility:1219111129297024974")
    private static final long serialVersionUID = 1L;
	public static final String DEF_MSG = "EmployeeCivilIdNotExistException";
	public static final String MSG_KEY = "EmployeeCivilIdNotExistException";
	public static final String BDL_KEY = "EmployeeCivilIdNotExistException";

	public EmployeeCivilIdNotExistException(String message, Throwable e, String bundleKey, String messageKey){
	super(message, e, bundleKey, messageKey);
	}


	public EmployeeCivilIdNotExistException(String message, Throwable e, String messageKey){
	super(message, e, BDL_KEY, messageKey);
	}


	public EmployeeCivilIdNotExistException(String message, Throwable e){
	super(message, e, BDL_KEY, MSG_KEY);
	}


	public EmployeeCivilIdNotExistException(Throwable e, String bundleKey, String messageKey){
	super(DEF_MSG, e, bundleKey, messageKey);
	}


	public EmployeeCivilIdNotExistException(Throwable e, String messageKey){
	super(DEF_MSG, e, BDL_KEY, messageKey);
	}


	public EmployeeCivilIdNotExistException(Throwable e){
	super(DEF_MSG, e, BDL_KEY, MSG_KEY);
	}


	public EmployeeCivilIdNotExistException(String message, String bundleKey, String messageKey){
	super(message, bundleKey, messageKey);
	}


	public EmployeeCivilIdNotExistException(String message, String messageKey){
	super(message, BDL_KEY, messageKey);
	}


    public EmployeeCivilIdNotExistException() {

	super(DEF_MSG, BDL_KEY, MSG_KEY);

    }

	public EmployeeCivilIdNotExistException(String message){

	super(message, BDL_KEY, MSG_KEY);

    }
}
